# Shared shell aliases, kept declarative here and rendered to a POSIX-neutral
# file sourced by both the HM-managed .zshrc and (on pasokon) the
# Omarchy-managed .bashrc. Add aliases here, run `home-manager switch`, done.
#
# Cross-platform only. Host-specific aliases go in the host's own alias file
# (modules/linux/aliases.nix, or the work flake's host file), which renders to
# ~/.config/shell/aliases-host.sh and is sourced after this one.
#
# NOTE: this fragment is sourced with mkAfter, so it overrides
# programs.zsh.shellAliases. A host alias set in `shellAliases` will be silently
# shadowed by anything here — put host aliases in aliases-host.sh instead.
{ lib, ... }:
let
  shellAliases = {
    e = "nvim";
    music = "cliamp --provider ytmusic";

    # Claude Code, skipping permission prompts.
    cx = "claude --dangerously-skip-permissions";
    c = "opencode";

    ".." = "cd ..";
    "..." = "cd ../..";
    "...." = "cd ../../..";

    # `cd` falls through to a zoxide fuzzy jump when the argument is not a real
    # directory. zd() is defined in zsh/tool-inits.zsh; it calls `j`, which is
    # zoxide's command name here.
    cd = "zd";

    d = "docker";
    g = "git";
    r = "rails";

    # eza-flavoured ls (from omanix)
    ls = "eza -lh --group-directories-first --icons=auto";
    ll = "eza -l --icons=auto";
    la = "eza -la --icons=auto";
    lt = "eza --tree --level=2 --long --icons --git";

    # bat as a plain-pager cat (from omanix)
    cat = "bat -pp";
  };

  renderAlias = name: value: "alias ${name}=${lib.escapeShellArg value}";
  body = lib.concatStringsSep "\n" (lib.mapAttrsToList renderAlias shellAliases);
in
{
  xdg.configFile."shell/aliases.sh".text = ''
    # Generated by Home Manager (modules/common/aliases.nix). Do not edit here.
    ${body}
  '';
}
