# Shell aliases, kept declarative here and rendered to a POSIX-neutral file that
# your Omarchy-managed .zshrc/.bashrc source. This keeps Home Manager out of the
# rc files themselves (Omarchy owns those) while still owning the alias list.
#
# Add aliases here, run `home-manager switch`, done. No rc-file editing.
{ lib, ... }:
let
  # Absolute --flake path so these work from any directory, not just the repo.
  flakeDir = "~/Work/tries/2026-07-01-nix-config";

  shellAliases = {
    e = "nvim";
    music = "cliamp --provider ytmusic";

    # Home Manager
    hms = "home-manager switch --flake ${flakeDir}#foomaxchu@pasokon";
    hmu = "nix flake update --flake ${flakeDir} && home-manager switch --flake ${flakeDir}#foomaxchu@pasokon";
  };

  renderAlias = name: value: "alias ${name}=${lib.escapeShellArg value}";
  body = lib.concatStringsSep "\n" (lib.mapAttrsToList renderAlias shellAliases);
in
{
  xdg.configFile."shell/aliases.sh".text = ''
    # Generated by Home Manager (modules/shared/aliases.nix). Do not edit here.
    ${body}
  '';
}
