# Shell aliases, kept declarative here and rendered to a POSIX-neutral file that
# your Omarchy-managed .zshrc/.bashrc source. This keeps Home Manager out of the
# rc files themselves (Omarchy owns those) while still owning the alias list.
#
# Add aliases here, run `home-manager switch`, done. No rc-file editing.
{ lib, ... }:
let
  shellAliases = {
    e = "nvim";
    music = "cliamp --provider ytmusic";
  };

  renderAlias = name: value: "alias ${name}=${lib.escapeShellArg value}";
  body = lib.concatStringsSep "\n" (lib.mapAttrsToList renderAlias shellAliases);
in
{
  xdg.configFile."shell/aliases.sh".text = ''
    # Generated by Home Manager (modules/shared/aliases.nix). Do not edit here.
    ${body}
  '';
}
