# Linux/pasokon-only aliases, appended to the shared alias fragment.
#
# These name this host's flake target, so they must not be shared: on the work
# Mac `hms` would rebuild the wrong configuration.
{ lib, ... }:
let
  # Absolute --flake path so these work from any directory, not just the repo.
  flakeDir = "~/nix-config";
  target = "foomaxchu@pasokon";

  shellAliases = {
    # Home Manager. The # is backslash-escaped because zsh with EXTENDED_GLOB
    # treats an unquoted # as a glob operator when the alias text is expanded.
    hms = "home-manager switch --flake ${flakeDir}\\#${target}";
    hmu = "nix flake update --flake ${flakeDir} && home-manager switch --flake ${flakeDir}\\#${target}";

    # Omarchy/Linux desktop bits.
    lzd = "lazydocker";
  };

  renderAlias = name: value: "alias ${name}=${lib.escapeShellArg value}";
  body = lib.concatStringsSep "\n" (lib.mapAttrsToList renderAlias shellAliases);
in
{
  xdg.configFile."shell/aliases-host.sh".text = ''
    # Generated by Home Manager (modules/linux/aliases.nix). Do not edit here.
    ${body}
  '';
}
