# Shell aliases, kept declarative here and rendered to a POSIX-neutral file
# sourced by both the HM-managed .zshrc and the Omarchy-managed .bashrc.
# Add aliases here, run `home-manager switch`, done. No rc-file editing.
{ lib, ... }:
let
  # Absolute --flake path so these work from any directory, not just the repo.
  flakeDir = "~/nix-config";

  shellAliases = {
    e = "nvim";
    music = "cliamp --provider ytmusic";

    # Home Manager. The # is backslash-escaped because zsh with EXTENDED_GLOB
    # treats an unquoted # as a glob operator when the alias text is expanded.
    hms = "home-manager switch --flake ${flakeDir}\\#foomaxchu@pasokon";
    hmu = "nix flake update --flake ${flakeDir} && home-manager switch --flake ${flakeDir}\\#foomaxchu@pasokon";

    ".." = "cd ..";
    "..." = "cd ../..";
    "...." = "cd ../../..";

    # eza-flavoured ls (from omanix)
    ls = "eza -lh --group-directories-first --icons=auto";
    ll = "eza -l --icons=auto";
    la = "eza -la --icons=auto";
    lt = "eza --tree --level=2 --long --icons --git";

    # macOS-style clipboard on Wayland (from omanix)
    pbcopy = "wl-copy --type text/plain";
    pbpaste = "wl-paste";

    # bat as a plain-pager cat (from omanix)
    cat = "bat -pp";
  };

  renderAlias = name: value: "alias ${name}=${lib.escapeShellArg value}";
  body = lib.concatStringsSep "\n" (lib.mapAttrsToList renderAlias shellAliases);
in
{
  xdg.configFile."shell/aliases.sh".text = ''
    # Generated by Home Manager (modules/core/aliases.nix). Do not edit here.
    ${body}
  '';
}
